//
// Created by urdmi on 11.08.2024.
//

#ifndef STM32L4CMSIS_MCU_H
#define STM32L4CMSIS_MCU_H

#define MCU__GPIO_PORT_A        (0x00)
#define MCU__GPIO_PORT_B        (0x01)
#define MCU__GPIO_PORT_C        (0x02)
#define MCU__GPIO_PORT_D        (0x03)
#define MCU__GPIO_PORT_E        (0x04)

#define MCU__GPIO_PIN_0         (0x00)
#define MCU__GPIO_PIN_1         (0x01)
#define MCU__GPIO_PIN_2         (0x02)
#define MCU__GPIO_PIN_3         (0x03)
#define MCU__GPIO_PIN_4         (0x04)
#define MCU__GPIO_PIN_5         (0x05)
#define MCU__GPIO_PIN_6         (0x06)
#define MCU__GPIO_PIN_7         (0x07)
#define MCU__GPIO_PIN_8         (0x08)
#define MCU__GPIO_PIN_9         (0x09)
#define MCU__GPIO_PIN_10        (0x0A)
#define MCU__GPIO_PIN_11        (0x0B)
#define MCU__GPIO_PIN_12        (0x0C)
#define MCU__GPIO_PIN_13        (0x0D)
#define MCU__GPIO_PIN_14        (0x0E)
#define MCU__GPIO_PIN_15        (0x0F)

#define MCU__PORT_A_PIN_0 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_0) << 3))
#define MCU__PORT_A_PIN_1 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_1) << 3))
#define MCU__PORT_A_PIN_2 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_2) << 3))
#define MCU__PORT_A_PIN_3 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_3) << 3))
#define MCU__PORT_A_PIN_4 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_4) << 3))
#define MCU__PORT_A_PIN_5 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_5) << 3))
#define MCU__PORT_A_PIN_6 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_6) << 3))
#define MCU__PORT_A_PIN_7 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_7) << 3))
#define MCU__PORT_A_PIN_8 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_8) << 3))
#define MCU__PORT_A_PIN_9 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_9) << 3))
#define MCU__PORT_A_PIN_10 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_10) << 3))
#define MCU__PORT_A_PIN_11 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_11) << 3))
#define MCU__PORT_A_PIN_12 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_12) << 3))
#define MCU__PORT_A_PIN_13 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_13) << 3))
#define MCU__PORT_A_PIN_14 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_14) << 3))
#define MCU__PORT_A_PIN_15 ((MCU__GPIO_PORT_A) | ((MCU__GPIO_PIN_15) << 3))

#define MCU__PORT_B_PIN_0 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_0) << 3))
#define MCU__PORT_B_PIN_1 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_1) << 3))
#define MCU__PORT_B_PIN_2 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_2) << 3))
#define MCU__PORT_B_PIN_3 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_3) << 3))
#define MCU__PORT_B_PIN_4 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_4) << 3))
#define MCU__PORT_B_PIN_5 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_5) << 3))
#define MCU__PORT_B_PIN_6 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_6) << 3))
#define MCU__PORT_B_PIN_7 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_7) << 3))
#define MCU__PORT_B_PIN_8 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_8) << 3))
#define MCU__PORT_B_PIN_9 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_9) << 3))
#define MCU__PORT_B_PIN_10 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_10) << 3))
#define MCU__PORT_B_PIN_11 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_11) << 3))
#define MCU__PORT_B_PIN_12 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_12) << 3))
#define MCU__PORT_B_PIN_13 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_13) << 3))
#define MCU__PORT_B_PIN_14 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_14) << 3))
#define MCU__PORT_B_PIN_15 ((MCU__GPIO_PORT_B) | ((MCU__GPIO_PIN_15) << 3))

#define MCU__PORT_C_PIN_0 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_0) << 3))
#define MCU__PORT_C_PIN_1 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_1) << 3))
#define MCU__PORT_C_PIN_2 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_2) << 3))
#define MCU__PORT_C_PIN_3 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_3) << 3))
#define MCU__PORT_C_PIN_4 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_4) << 3))
#define MCU__PORT_C_PIN_5 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_5) << 3))
#define MCU__PORT_C_PIN_6 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_6) << 3))
#define MCU__PORT_C_PIN_7 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_7) << 3))
#define MCU__PORT_C_PIN_8 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_8) << 3))
#define MCU__PORT_C_PIN_9 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_9) << 3))
#define MCU__PORT_C_PIN_10 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_10) << 3))
#define MCU__PORT_C_PIN_11 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_11) << 3))
#define MCU__PORT_C_PIN_12 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_12) << 3))
#define MCU__PORT_C_PIN_13 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_13) << 3))
#define MCU__PORT_C_PIN_14 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_14) << 3))
#define MCU__PORT_C_PIN_15 ((MCU__GPIO_PORT_C) | ((MCU__GPIO_PIN_15) << 3))

#define MCU__PORT_D_PIN_0 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_0) << 3))
#define MCU__PORT_D_PIN_1 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_1) << 3))
#define MCU__PORT_D_PIN_2 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_2) << 3))
#define MCU__PORT_D_PIN_3 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_3) << 3))
#define MCU__PORT_D_PIN_4 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_4) << 3))
#define MCU__PORT_D_PIN_5 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_5) << 3))
#define MCU__PORT_D_PIN_6 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_6) << 3))
#define MCU__PORT_D_PIN_7 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_7) << 3))
#define MCU__PORT_D_PIN_8 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_8) << 3))
#define MCU__PORT_D_PIN_9 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_9) << 3))
#define MCU__PORT_D_PIN_10 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_10) << 3))
#define MCU__PORT_D_PIN_11 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_11) << 3))
#define MCU__PORT_D_PIN_12 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_12) << 3))
#define MCU__PORT_D_PIN_13 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_13) << 3))
#define MCU__PORT_D_PIN_14 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_14) << 3))
#define MCU__PORT_D_PIN_15 ((MCU__GPIO_PORT_D) | ((MCU__GPIO_PIN_15) << 3))

#define MCU__PORT_E_PIN_0 ((MCU__GPIO_PORT_E) | ((MCU__GPIO_PIN_0) << 3))
#define MCU__PORT_E_PIN_1 ((MCU__GPIO_PORT_E) | ((MCU__GPIO_PIN_1) << 3))
#define MCU__PORT_E_PIN_2 ((MCU__GPIO_PORT_E) | ((MCU__GPIO_PIN_2) << 3))
#define MCU__PORT_E_PIN_3 ((MCU__GPIO_PORT_E) | ((MCU__GPIO_PIN_3) << 3))
#define MCU__PORT_E_PIN_4 ((MCU__GPIO_PORT_E) | ((MCU__GPIO_PIN_4) << 3))

#define MCU__USART_1        (0x00)
#define MCU__USART_COUNT    1

#endif //STM32L4CMSIS_MCU_H
